name: Build Application

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Change to the version you need
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the application
      - name: Build the application
        run: npm run build

  docker-hub:
      runs-on: ubuntu-latest
      needs: build
      steps:
        # Checkout the code
        - name: Checkout code
          uses: actions/checkout@v3
  
        # Log in to DockerHub
        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
        # Build the Docker image
        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mementune-matching:latest -f ./Dockerfile .
  
        # Push the Docker image
        - name: Push Docker image
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mementune-matching:latest
